pipeline {
    agent {label 'maven'}
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy to Nexus') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'nexus-creds',      // This ID is from Jenkins Credentials store
                    usernameVariable: 'NEXUS_USER',
                    passwordVariable: 'NEXUS_PASSWORD'
                )]) {
                    sh '''
                    mvn -f java-tomcat-sample/pom.xml deploy \
                    -Dnexus.username=$NEXUS_USER \
                    -Dnexus.password=$NEXUS_PASSWORD
                    '''
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                echo "done thank you"

            }
            
        }
        
}
}
